apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sureshsri12/Argocd.git
    path: dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-namespace-1
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true