apiVersion: v1
kind: Namespace
metadata:
  name: sample-app-namespace-1
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-app-namespace-1
  namespace: sample-app-namespace-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-namespace-1
  template:
    metadata:
      labels:
        app: sample-app-namespace-1
spec:
  nodeSelector:                  
    gpunode: 'true'  
    srtworkload: 'true'
  containers:
    - name: sample-app-namespace-1
      image: jenkinspipeline12/nodejssample:latest
      # resources:
      #       limits:
      #         cpu: "2"
      #         memory: "5Gi"
      #       requests:
      #         cpu: "2"
      #         memory: "5Gi"
      ports:
        - containerPort: 3000

